CREATE TABLE IF NOT EXISTS Reports (
    user_id UUID REFERENCES users(id) NOT NULL,
    type VARCHAR NOT NULL,
    filter TEXT NOT NULL,
    status VARCHAR NOT NULL,
    CONSTRAINT REPORTS_PK PRIMARY KEY (ID)
)INHERITS (AUDITABLE_ENTITY);
