version: '3'

services:
  spring-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cms-backend-service-app
    depends_on: [postgresql]
    ports:
      - "8081:8081"

  postgresql:
    image: postgres:latest
    container_name: postgresql-container
    ports:
     - "5432:5432"
    volumes:
     - /postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root